moma_ws/moma_ws/urls.py
from django.contrib import admin

from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('personal/', include('personal.urls'), name='personal'),
    path('wordcount/', include('wordcount.urls'), name='wordcount-api'),
    path('', include('artmonitors.urls'))
]

moma_ws/personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:name>', views.show_webpage, name='view_file')
]

moma_ws/personal/models.py
"""
A python file declaring the models used in this project.
Since this project is exclusively intended to host files of
personal importance and little else, the contained models
are very simple.
"""
__author__ = "Louis Jacobowitz <ldjacobowitzer@gmail.com>"

from django.db import models
import os

# Create your models here.


def generate_filename(instance, filename):
    print(filename)
    if instance.folder and len(instance.folder) > 0:
        print(os.path.join('personal', instance.folder, filename))
        return os.path.join('personal', instance.folder, filename)
    else:
        return 'personal/{}'.format(filename)


class PersonalFile(models.Model):
    """
    A model type representing a single file. Contains only that
    file object.
    """
    def __str__(self):
        return "{} ---> {}".format(self.name, str(self.file))

    """ The url for accessing this file """
    name = models.CharField(max_length=200)
    """ A description for this project """
    description = models.TextField(blank=True, null=True)
    """ Whether this item should be displayed on the projects index """
    display = models.BooleanField(default=True)
    """ A folder for this object to be placed in """
    folder = models.CharField(max_length=200, blank=True, null=True, default=None)
    """ The actual media url of the file """
    file = models.FileField(upload_to=generate_filename)

moma_ws/personal/views.py
import django.shortcuts
from django.http import HttpResponse
import moma_ws.settings as django_settings
from .models import PersonalFile
import datetime
import os

# Create your views here.


def index(request):
    personal_projects_list = PersonalFile.objects.filter(display=True)
    context = {
        'featured_projects': personal_projects_list,
        'copyright_year': str(datetime.datetime.now().year),
    }
    return django.shortcuts.render(request, 'personal/work_descriptions.html', context=context)


def show_webpage(request, name):
    file_obj = django.shortcuts.get_object_or_404(PersonalFile, name=name)
    context = {
        'resource_name': file_obj.name,
        'resource_url': django_settings.MEDIA_URL + str(file_obj.file)
    }
    print(context)
    return django.shortcuts.render(request, 'personal/redirect_to_file.html', context=context)

moma_ws/personal/templates/personal/redirect_to_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Redirect to {{ resource_name }}</title>
    <meta http-equiv="refresh" content="0; URL={{ resource_url }}">
    <meta name="keywords" content="automatic redirection">
</head>
<body>
    Trying to redirect you to the requested content. If your browser doesn't go there automatically,
    <a href="{{ resource_url }}">click here</a> .
</body>
</html>

moma_ws/personal/templates/personal/work_descriptions.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>Non-MOMA Projects</title>
</head>
<body>
    <div id="header">Monitors of Modern Art</div>
    <div id="container">
        <div id="menu">
            {% include 'artmonitors/menu.html' %}
        </div>
        <div id="content">
            <div class="puretext">
                <p class="centeredText">You've stumbled upon a list of my Non-MOMA projects! These have no relation to
                    Monitors of Modern Art, and the reason they're stored on this website is principally because I have
                    the website anyway so I might as well use it for this and save the money of buying another.</p><br>
                <p class="centeredText">Thank you, and please enjoy!</p>
            </div>
            {% for project in featured_projects %}
            <div class="puretext">
		    <!-- <h1>{{ project.name }}</h1> -->
                {% if project.description %}
                    <p>{{ project.description|safe }}</p>
                {% endif %}
                <p><a href="{% url 'personal:view_file' name=project.name %}">Click here to view this project.</a></p>
            </div>
            {% endfor %}
        </div>
        <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
    </div>
</body>
</html>