moma_ws/artmonitors/urls.py
"""
A django-required file for determining the set of URLs for this site
"""

from django.urls import include, path

from . import views

app_name = 'artmonitors'
urlpatterns = [
    # top-level directory, show index
    path('',                                                views.index,                name='index'),
    # view list of collections
    path('collections/',                                    views.view_all_collections, name='view_all_collections'),
    # view specific collection
    path('collections/<slug:coll_abbrev>',                  views.view_collection,      name='view_collection'),
    # view specific work page
    path('collections/<slug:coll_abbrev>/<slug:work_name>', views.view_work,            name='view_work'),
    # view archive
    path('archive',                                         views.view_archive,         name='view_archive'),
    path('archive/full',                                    views.view_full_archive,    name='view_full_archive'),
    path(r'archive/<slug:page_num>',                        views.view_archive_page,    name='view_archive_page'),
    # view about page
    path('about',                                           views.about_us,             name='view_about'),
    # view contact page
    path('contact',                                         views.contact_us,           name='view_contact'),
    # slideshow index
    path('slideshow',                                       views.slideshow,            name='slideshow'),
    path('group',                                           views.group,                name='group'),
    path('slideshow/<slug:group_name>',                     views.slideshow_group,      name='slideshow_group'),

    # admin add-collection page
    path('add_collection',                                  views.add_collection),
    path('preload_collection',                              views.preload_collection),
    path('upload_preloaded',                              views.upload_preloaded_collection),
    path('projects/',                                       include('personal.urls')),

    # test
    path('last_update_date',                                views.get_last_update,      name='last_update'),

    # old paths/redirectors
    path('about.html',                                      views.about_us,             name='old_about'),
    path('contact.html',                                    views.contact_us,           name='old_contact'),
    path('archive.html',                                    views.view_archive,         name='old_archive'),
    path('pages',                                           views.view_all_collections, name='old_pages'),
    path('pages/index.html',                                views.view_all_collections, name='old_pages_idx'),
    path('pages/<slug:coll_abbrev>',                        views.view_collection,      name='old_view_collection'),
    path('pages/<slug:coll_abbrev>/index.html',             views.view_collection,      name='old_view_collection_idx'),
    path('pages/<slug:coll_abbrev>/<slug:work_name>.html',  views.view_work,            name='old_view_work')
]

moma_ws/moma_ws/urls.py
from django.contrib import admin

from django.urls import include, path, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('personal/', include('personal.urls'), name='personal'),
    path('wordcount/', include('wordcount.urls'), name='wordcount-api'),
    path('', include('artmonitors.urls'))
]

moma_ws/personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'
urlpatterns = [
    path('', views.index, name='index'),
    path('<slug:name>', views.show_webpage, name='view_file')
]

moma_ws/artmonitors/views.py
# from django.shortcuts import render

import django.shortcuts
import django.http
from rest_framework.parsers import JSONParser
from django.views.decorators.csrf import csrf_exempt

import datetime
import json
import base64
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
import random
import string
import traceback
import math
import os
import sys
import smtplib, email

import moma_ws.settings as django_settings
from .models import Collection, TemplateCollection, Work, group_works
from .add_collection_utils import create_collection, \
    preload_collection as core_preload_collection, unload_collection as core_unload_collection

# Create your views here.


def index(request):
    """
    Presents the index page of this website, displaying the most recent new collection
    and several featured works from the history of the website.
    """
    # get newest collection from database
    newest_collection = Collection.objects.latest('id')
    # get featured works
    featured_works = random.sample(list(Work.objects.filter(featured=True)), 5)
    # get datetime of last monday
    last_monday = django_settings.LAST_UPDATE_DATE
    # prepare context
    context = {
        'newest_coll': newest_collection,
        'featured_works': featured_works,
        'last_monday_date': last_monday.strftime('%d %B %Y'),
        'copyright_year': datetime.datetime.now().year
    }
    return django.shortcuts.render(request, 'artmonitors/index.html', context)


def get_last_update(request):
    return str(django_settings.LAST_UPDATE_DATE)


def view_all_collections(request):
    """
    Presents a view of all collections' abbreviations and names, in a list
    """
    # get all collection database objects
    collections = sorted(Collection.objects.all())
    # build context
    context = {
        'collections': collections,
        'copyright_year': str(datetime.datetime.now().year)
    }
    return django.shortcuts.render(request, 'artmonitors/all_collections.html', context)


def view_collection(request, coll_abbrev):
    """
    Presents a view of a particular collection, including its description and
    thumbnails of each work it contains
    """
    # get regular database objects
    collection = django.shortcuts.get_object_or_404(Collection, abbrev=coll_abbrev)
    debug_collection = django.shortcuts.get_object_or_404(Collection, abbrev='macc2')
    print(collection)
    print(debug_collection)

    # get prev and next collections
    try:
        prev_collection = Collection.objects.get(id=collection.id - 0.5)
    except Collection.DoesNotExist:
        try:
            prev_collection = Collection.objects.get(id=collection.id - 1)
        except Collection.DoesNotExist:
            prev_collection = None
    try:
        next_collection = Collection.objects.get(id=collection.id + 0.5)
    except Collection.DoesNotExist:
        try:
            next_collection = Collection.objects.get(id=collection.id + 1)
        except Collection.DoesNotExist:
            next_collection = None
    # get works, and group them appropriately
    works = sorted(Work.objects.filter(collection=collection))
    debug_works = sorted(Work.objects.filter(collection=debug_collection))

    print(works)
    print(debug_works)


    work_groups = group_works(works, 3)
    # build context
    context = {
        'coll': collection,
        'prev_coll': prev_collection,
        'next_coll': next_collection,
        'work_groups': work_groups,
        'copyright_year': datetime.datetime.now().year
    }
    # return page template accordingly
    return django.shortcuts.render(request, 'artmonitors/view_collection.html', context)


def view_work(request, coll_abbrev, work_name):
    """
    Presents a view of a particular work, including its title, image, and
    description, if it has one
    """
    # get regular database objects for these
    collection = django.shortcuts.get_object_or_404(Collection, abbrev=coll_abbrev)
    work = django.shortcuts.get_object_or_404(Work, collection=collection, pagename=work_name)
    # get previous and next works
    try:
        prev_work = Work.objects.get(id=work.id - 1)
    except Work.DoesNotExist:
        prev_work = None
    try:
        next_work = Work.objects.get(id=work.id + 1)
    except Work.DoesNotExist:
        next_work = None
    # build context
    context = {
        'collection': collection,
        'work': work,
        'prev_work': prev_work,
        'next_work': next_work,
        'copyright_year': str(datetime.datetime.now().year)
    }
    # return page template accordingly
    return django.shortcuts.render(request, 'artmonitors/view_work.html', context)


def view_archive(request):
    """
    Presents a view of the names of all works currently existing in the collection,
    in order of most recent
    """
    # get database objects for works
    works = sorted(Work.objects.all())
    works.reverse()
    work_groups = group_works(works, 5)
    # build context
    context = {
        'work_groups': work_groups,
        'copyright_year': datetime.datetime.now().year
    }
    return django.shortcuts.render(request, 'artmonitors/archive_text.html', context)


def view_full_archive(request):
    """
    Presents a view of thumbnails and names of all works currently existing in the
    collection, in order of most recent
    """
    # get database objects for works
    works = sorted(Work.objects.all())
    works.reverse()
    work_groups = group_works(works, 3)
    # build context
    context = {
        'work_groups': work_groups,
        'copyright_year': datetime.datetime.now().year
    }
    return django.shortcuts.render(request, 'artmonitors/archive_full.html', context)

def view_archive_page(request, page_num):
    """
    Presents a view of the 'page_num'th 60 works in the archive.
    """
    # validate page_num is an integer and turn it into one
    try:
        current_page = int(page_num)
    except ValueError:
        return django.http.HttpResponseBadRequest()
    page_num = current_page - 1

    # get database objects for works
    works = sorted(Work.objects.all())
    works.reverse()

    # filter works
    works_per_page = 60
    if page_num * works_per_page > len(works) or page_num < 0:
        return django.http.Http404()
    elif (page_num + 1) * works_per_page > len(works):
        filtered_works = works[page_num * works_per_page:]
    else:
        filtered_works = works[page_num * works_per_page:(page_num + 1) * works_per_page]

    # group filtered works together
    work_groups = group_works(filtered_works, 3)
    max_page_num = math.ceil(len(works) / works_per_page)

    # build context
    context = {
        'works_per_page': works_per_page,
        'current_page': current_page,
        'page_list': range(1, max_page_num + 1),  # [1, 2, 3, 4, ..., max_page_num].
        'work_groups': work_groups,
        'copyright_year': datetime.datetime.now().year
    }
    return django.shortcuts.render(request, 'artmonitors/archive_page.html', context)


def about_us(request):
    """
    Returns a simple "About Us" page
    """
    context = {
        'copyright_year': str(datetime.datetime.now().year)
    }
    return django.shortcuts.render(request, 'artmonitors/about_us.html', context)


def contact_us(request):
    """
    Returns a simple "Contact Us" page
    """
    context = {
        'copyright_year': str(datetime.datetime.now().year)
    }
    return django.shortcuts.render(request, 'artmonitors/contact_us.html', context)


def slideshow(request):
    all_works = [[str(work.name), os.path.join('/static/media', str(work.path)), str(work.pagename),
                  str(work.collection.abbrev)] for work in Work.objects.all()]
    context = {
        'work_list': json.dumps(all_works)
    }
    return django.shortcuts.render(request, 'artmonitors/slideshow.html', context)


################################################################################################
# Helper methods for regular operations
################################################################################################


def slideshow_group(request, group_name):
    context = {
        'group_name': group_name
    }
    return django.shortcuts.render(request, 'artmonitors/slideshow_groups.html', context)


def group(request):
    collections = {c: group_works([w for w in Work.objects.filter(collection=c)], 3) for c in Collection.objects.all()}
    collection_info = {str(c.id): {
        'abbrev': str(c.abbrev),
        'name': str(c.name),
        'works': {
            str(w.id): {
                'name': str(w.name),
                'path': str(w.path),
                'filename': str(w.filename),
                'pagename': str(w.pagename),
                'thumbnail': str(w.thumbnail),
                'selected': str(True),
            } for w in Work.objects.filter(collection=c)
        },
    } for c in collections}
    selected_collection = Collection.objects.get(id=1)
    selected_works = collections[selected_collection]
    # works = {c.id: group_works([w for w in Work.objects.filter(collection=c)], 3) for c in collections}

    print(str(collection_info))

    context = {
        'copyright_year': str(datetime.datetime.now().year),
        'collections': collections,
        'collection_info': json.dumps(collection_info),
        'selected_collection': selected_collection,
        'selected_works': selected_works
        # 'works': works
    }
    print(collections)
    return django.shortcuts.render(request, 'artmonitors/group.html', context)


################################################################################################
# add_collection routines and helper methods
################################################################################################

# declare decryption message for decryption
def decrypt_message(encoded_encrypted_msg, private_key):

moma_ws/artmonitors/templates/artmonitors/archive_full.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>Archive - Monitors of Modern Art</title>
    <meta property="og:title" content="Monitors of Modern Art - Archive" />
    <meta property="og:description" content="View the names and thumbnails of every work of modern art ever shown in the Monitors of Modern Art gallery!" />
    <meta property="og:site_name" content="https://artmonitors.com" />
</head>
<body>
<div id="header">Monitors of Modern Art</div>
<div id="container">
    <div id="menu">
        {% include 'artmonitors/menu.html' %}
    </div>
    <div id="content">
        <div class="puretext">
            <h1><u>Full Image Archive</u></h1>
            <center>
                <p class="puretext">This archive displays thumbnail images for every work ever published on this website, in order of most
                recent, along with
                those works' names. However, even using only thumbnails, this is a very high-bandwidth page; if you
                only need to see the names of these works, feel free to visit <a
                    href="{% url 'artmonitors:view_archive' %}">
                our text-only archive</a>, or individually browse our <a
                    href="{% url 'artmonitors:view_all_collections' %}">
                        collections</a> to see less images at once.</p> You can also view our <a
                    href="{% url 'artmonitors:view_archive_page' page_num=1 %}">tabulated, page-based
                archive</a>, which might be easier on your bandwidth.
            </center>
        </div>
        <div class="post">
            <br>
            <center>
                <table style="width=100%;">
                    {% for group in work_groups %}
                    <tr>
                        {% for work in group %}
                        <td>
                            <a href="{% url 'artmonitors:view_work' coll_abbrev=work.collection.abbrev work_name=work.pagename %}">
                                <img src="{% get_media_prefix %}/{{ work.thumbnail }}"><br>
                                <p>{{ work.name }}</p>
                            </a>
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            </center>
        </div>
    </div>
    <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
</div>
</body>
</html>

moma_ws/artmonitors/templates/artmonitors/archive_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>Archive - Monitors of Modern Art</title>
    <meta property="og:title" content="Monitors of Modern Art - Archive" />
    <meta property="og:description" content="View the names and thumbnails of every work of modern art ever shown in the Monitors of Modern Art gallery!" />
    <meta property="og:site_name" content="https://artmonitors.com" />
</head>
<body>
<div id="header">Monitors of Modern Art</div>
<div id="container">
    <div id="menu">
        {% include 'artmonitors/menu.html' %}
    </div>
    <div id="content">
        <div class="puretext">
            <h1><u>Full Image Archive (Page {{ current_page }})</u></h1>
            <center>
                <p class="puretext">This archive displays thumbnail images for every work ever published on this website, in order of most
                recent, along with
                those works' names. However, even using only thumbnails, this is a very high-bandwidth page; if you
                only need to see the names of these works, feel free to visit <a
                    href="{% url 'artmonitors:view_archive' %}">
                our text-only archive</a>, or individually browse our <a
                    href="{% url 'artmonitors:view_all_collections' %}">
                        collections</a> to see less images at once.</p>
            </center>
        </div>

        <div class="post">
            <h2>View page ({{ works_per_page }} works per page):</h2><br>

            {% for page in page_list %}
            {% if page == current_page %}
            {{ page }}
            {% else %}
            <a href="{% url 'artmonitors:view_archive_page' page_num=page %}">{{ page }}</a>
            {% endif %}
            {% endfor %}
        </div>

        <div class="post">
            <br>
            <center>
                <table style="width=100%;">
                    {% for group in work_groups %}
                    <tr>
                        {% for work in group %}
                        <td>
                            <a href="{% url 'artmonitors:view_work' coll_abbrev=work.collection.abbrev work_name=work.pagename %}">
                                <img src="{% get_media_prefix %}/{{ work.thumbnail }}"><br>
                                <p>{{ work.name }}</p>
                            </a>
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            </center>
        </div>

        <div class="post">
            <h2>View page ({{ works_per_page }} works per page):</h2><br>

            {% for page in page_list %}
            {% if page == current_page %}
            {{ page }}
            {% else %}
            <a href="{% url 'artmonitors:view_archive_page' page_num=page %}">{{ page }}</a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
</div>
</body>
</html>

moma_ws/artmonitors/templates/artmonitors/archive_text.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>Archive - Monitors of Modern Art</title>
    <meta property="og:title" content="Monitors of Modern Art - Archive" />
    <meta property="og:description" content="View the names of every work of modern art ever shown in the Monitors of Modern Art gallery!" />
    <meta property="og:site_name" content="https://artmonitors.com" />
</head>
<body>
<div id="header">Monitors of Modern Art</div>
<div id="container">
    <div id="menu">
        {% include 'artmonitors/menu.html' %}
    </div>
    <div id="content">
        <div class="puretext">
            <h1><u>Text-Only Archive</u></h1>
            <center>
                <p class="puretext">This archive displays the names of every work ever published on this website, in order of most recent. Only
                the name of each work is shown, and so this archive is intended for when you just can't quite remember which
                collection a work was in. If you want to see a catalogue of images instead (rather than just the names), we
                recommend checking out <a href="{% url 'artmonitors:view_archive_page' page_num=1 %}">the version of the archive that
                contains thumbnail images</a> (warning: this may consume a lot of your bandwidth), or browse our <a
                            href="{% url 'artmonitors:view_all_collections' %}">collection pages</a> instead.</p>
            </center>
        </div>
        <div class="post">
            <center>
                <table style="width=100%;">
                    {% for group in work_groups %}
                    <tr>
                        {% for work in group %}
                        <td>
                            <a href="{% url 'artmonitors:view_work' coll_abbrev=work.collection.abbrev work_name=work.pagename %}">
                                {{ work.name }}
                            </a>
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            </center>
        </div>
    </div>
    <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
</div>
</body>
</html>

moma_ws/artmonitors/templates/artmonitors/contact_us.html
<!DOCTYPE html>
<html lang="en">
	<head>
        {% load static %}
		<link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
		<link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
		<meta http-equiv="Content-type" content="text/html;charset=utf-8">
		<title>Contact Us - Monitors of Modern Art</title>
		<meta property="og:title" content="Monitors of Modern Art - Contact Us" />
		<meta property="og:description" content="Send an email to the curator of Monitors of Modern Art!" />
    	<meta property="og:site_name" content="https://artmonitors.com" />
	</head>
	<body>
		<div id="header">Monitors of Modern Art</div>
		<div id="container">
			<div id="menu">
				{% include 'artmonitors/menu.html' %}
			</div>
			<div id="content">
				<div class="puretext">
					<h1>Contact Us</h1>
					<p>If you'd like to communicate with MOMA for any reason, be it sharing your work,
                        informing us of bugs in our website, guessing the title of a collection, or
                        anything else, we invite you to write an E-mail to
                        <a href="mailto:curator@artmonitors.com">curator@artmonitors.com</a>.</p>
				</div>
			</div>
			<div id="footer">&copy Louis Jacobowitz 2018</div>
		</div>
	</body>
</html>

moma_ws/artmonitors/templates/artmonitors/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <title>Monitors of Modern Art</title>
    <meta name="Description" content="An art gallery featuring all sorts of unique and colorful abstract art, compiled here for your viewing pleasure.">
    <meta property="og:description"
          content="An art gallery featuring all sorts of unique and colorful abstract art, compiled here for your viewing pleasure. The most recent collection is {{ newest_coll.abbrev|upper }}">
    <meta property="og:title" content="Monitors of Modern Art" />
    <meta property="og:image" content="{% get_media_prefix %}/{{ featured_works.1.path }}" />
    <meta property="og:site_name" content="https://artmonitors.com" />

    <script src="{% static 'artmonitors/set_height.js' %}"></script>
   <!-- <script>
        window.addEventListener("resize", setGoodHeightForAll)
    </script>-->
</head>
<body>
<div id="header">Monitors of Modern Art</div>
<div id="container">
    <div id="menu">
        {% include 'artmonitors/menu.html' %}
    </div>
    <div id="content">
        <div class="post">
            <p class="centeredText">Hello, and welcome to Monitors of Modern Art!</p>
            <p class="centeredText">You can learn more about MOMA <a href="{% url 'artmonitors:view_about' %}">here</a>,
                browse our various <a href="{% url 'artmonitors:view_all_collections' %}">collections</a>, experience an
                endless <a href="{% url 'artmonitors:slideshow' %}">slideshow</a> of our works, or look below for some
                highlights of the gallery's best works.</p>
            <br>
            <p class="centeredText">(Warning: This site is not for mobile users browsing on data. Our images are large,
                mostly uncompressed, and very data-intensive, so it is advised to view this website on a fast wi-fi
                connection.)</p>
        </div>
        <!-- new collection post -->
        <div class="post">
            <table class="new">
                <tr>
                    <td class="image">
                        <a href="{% url 'artmonitors:view_collection' coll_abbrev=newest_coll.abbrev %}">
                            <img class="title" src="{% get_media_prefix %}/{{ newest_coll.summary }}"
                                 align="left"
                                 onload="newNoteHeight(this);">
                        </a>
                    </td>
                    <td class="elsewise">
                        <h1>
                            <a href="{% url 'artmonitors:view_collection' coll_abbrev=newest_coll.abbrev %}">
                                Newest Collection: {{ newest_coll.abbrev|upper }} - {{ newest_coll.name }}
                            </a>
                        </h1>
                        <br>
                        <h2>{{ last_monday_date }}</h2>
                        <br>
                        <p class="puretext">This week's new collection is {{ newest_coll.abbrev|upper }}. {{ newest_coll.description|safe }}</p>
                    </td>
                </tr>
            </table>
        </div>
        <!-- posts for impressive past works -->
        {% for work in featured_works %}
        <div class="post">
            <h2><a href="{% url 'artmonitors:view_collection' coll_abbrev=work.collection.abbrev %}">
                {{ work.collection.abbrev|upper }}
            </a> > </h2>
            <h1>
                <a href="{% url 'artmonitors:view_work' coll_abbrev=work.collection.abbrev work_name=work.pagename %}">
                    {{ work.name|upper }}
                </a>
            </h1>
            <div class="imgcenter"><img class="work" src="{% get_media_prefix %}/{{ work.path }}"><br></div>
            {% if work.description %}
            <center><p class="puretext">{{ work.description|safe }}</p></center>
            {% endif %}
        </div>
        {% endfor %}
        </div>
    <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
</div>
</body>
</html>

moma_ws/artmonitors/templates/artmonitors/menu.html
<ul>
    {% load static %}
    <li><a href="{% url 'artmonitors:index' %}">Home</a></li>
    <li><a href="{% url 'artmonitors:view_archive' %}">Archive</a></li>
    <li><a href="{% url 'artmonitors:view_all_collections' %}">Collections</a></li>
    <li><a href="{% url 'artmonitors:group' %}">Slideshow</a></li>
    <li><a href="{% url 'artmonitors:view_about' %}">About</a></li>
    <li><a href="{% url 'artmonitors:view_contact' %}">Contact Us</a></li>
    <li>
        <a href="https://www.instagram.com/artmonitors/">
            <img class="ig" src="{% static 'artmonitors/Instagram_Glyph_Gradient_RGB.svg' %}"></a>
        <a href="https://www.instagram.com/artmonitors/">@artmonitors</a>
    </li>
</ul>

moma_ws/artmonitors/templates/artmonitors/view_collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'artmonitors/favicon.ico' %}"/>
    <link href="{% static 'artmonitors/artmonitors_stylesheet.css' %}" rel="stylesheet" type="text/css">
    <meta http-equiv="Content-type" content="text/html;charset=utf-8">
    <meta property="og:title" content="Collection {{ coll.abbrev|upper }} - Monitors of Modern Art" />
    <meta property="og:description" content="See all the works in {{ coll.abbrev | upper }}: {{ coll.name }}. {{ coll.description }}" />
    <meta property="og:site_name" content="https://artmonitors.com" />
    <title>{{ coll.abbrev|upper }} - {{ coll.name }} - Monitors of Modern Art</title>
    <script src="{% static 'artmonitors/set_height.js' %}"></script>
</head>
<body>
<div id="header">Monitors of Modern Art</div>
<div id="container">
    <div id="menu">
        {% include 'artmonitors/menu.html' %}
    </div>
    <div id="content">
        <div class="post">
            <h2><a href="{% url 'artmonitors:view_all_collections' %}">Collections</a> ></h2>
            <h1>{{ coll.abbrev|upper }} - {{ coll.name }}</h1>
            <h2>[
                {% if prev_coll %}
                    <a href="{% url 'artmonitors:view_collection' coll_abbrev=prev_coll.abbrev %}">Previous</a>
                {% if next_coll %} / {% endif %}
                {% endif %}
                {% if next_coll %}
                    <a href="{% url 'artmonitors:view_collection' coll_abbrev=next_coll.abbrev %}">Next</a>
                {% endif %} ]</h2><br>

            {% if coll.description %}
                <center>
                    <p class="puretext">
                        {{ coll.description|safe }}
                    </p>
                </center>
        </div>
        <div class="post">
            {% endif %}
            <center>
                <table>
                    {% for group in work_groups %}
                        <tr>
                            {% for work in group %}
                                <td>
                                    <a href="{% url 'artmonitors:view_work' coll_abbrev=coll.abbrev work_name=work.pagename %}">
                                        <img src="{% get_media_prefix %}/{{ work.thumbnail }}"><br>
                                        <p>{{ work.name }}</p>
                                    </a>
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </center>
        </div>
    </div>
    <div id="footer">&copy Louis Jacobowitz {{ copyright_year }}</div>
</div>
</body>
</html>